[CmdletBinding()]
param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$ErrorActionPreference = "Stop"
$Root = $Root.TrimEnd('\', '/')

function Get-Frontmatter {
    param([string]$Path)

    $text = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    $result = @{}
    if ($text -notmatch '(?s)^---\s*\r?\n(.*?)\r?\n---') {
        return $result
    }

    $block = $Matches[1]
    foreach ($line in ($block -split "\r?\n")) {
        if ($line -match '^\s*([A-Za-z0-9_-]+)\s*:\s*(.*)\s*$') {
            $key = $Matches[1].Trim()
            $value = $Matches[2].Trim()
            $result[$key] = $value.Trim('"').Trim("'")
        }
    }
    return $result
}

function Infer-DateFromName {
    param([string]$Name)
    if ($Name -match '(\d{4}-\d{2}-\d{2})') {
        return $Matches[1]
    }
    return "unknown"
}

function Infer-Provider {
    param([string]$Name)
    $lower = $Name.ToLowerInvariant()
    if ($lower -match 'claude-code') { return "Claude Code" }
    if ($lower -match 'claude') { return "Claude" }
    if ($lower -match 'codex') { return "Codex" }
    if ($lower -match 'chatgpt|gpt') { return "ChatGPT" }
    if ($lower -match 'powershell') { return "PowerShell" }
    return "unknown"
}

function Infer-Surface {
    param([string]$Name)
    $lower = $Name.ToLowerInvariant()
    if ($lower -match 'mobile') { return "mobile app" }
    if ($lower -match 'desktop') { return "desktop app" }
    if ($lower -match 'terminal|cli|powershell') { return "terminal" }
    if ($lower -match 'web') { return "web" }
    return "unknown"
}

function Escape-Cell {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) {
        return "unknown"
    }
    return ($Text -replace '\|', '\\|').Trim()
}

$rawDir = Join-Path $Root "raw"
$sourcesDir = Join-Path $Root "wiki\sources"
$outPath = Join-Path $Root "wiki\source-register.md"
$records = New-Object System.Collections.Generic.List[object]

if (Test-Path -LiteralPath $rawDir) {
    Get-ChildItem -LiteralPath $rawDir -Filter *.md -File | ForEach-Object {
        $fm = Get-Frontmatter $_.FullName
        $sourceDate = if ($fm.ContainsKey("source_date")) { $fm["source_date"] } elseif ($fm.ContainsKey("date")) { $fm["date"] } else { Infer-DateFromName $_.Name }
        if ($sourceDate -match '^(\d{4}-\d{2}-\d{2})') { $sourceDate = $Matches[1] }
        $provider = if ($fm.ContainsKey("source_provider")) { $fm["source_provider"] } else { Infer-Provider $_.Name }
        $surface = if ($fm.ContainsKey("source_surface")) { $fm["source_surface"] } else { Infer-Surface $_.Name }
        $project = if ($fm.ContainsKey("project")) { $fm["project"] } else { "unknown" }
        $title = if ($fm.ContainsKey("title")) { $fm["title"] } else { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
        $draftPath = Join-Path $sourcesDir $_.Name
        $draftRel = if (Test-Path -LiteralPath $draftPath) { "wiki/sources/$($_.Name)" } else { "" }

        $records.Add([PSCustomObject]@{
            SourceDate = $sourceDate
            Provider = $provider
            Surface = $surface
            Project = $project
            Title = $title
            RawPath = "raw/$($_.Name)"
            DraftPath = $draftRel
            SortDate = if ($sourceDate -match '^\d{4}-\d{2}-\d{2}$') { $sourceDate } else { "0000-00-00" }
        })
    }
}

$sorted = $records | Sort-Object @{ Expression = { $_.SortDate }; Descending = $true }, @{ Expression = { $_.Title }; Descending = $false }
$today = Get-Date -Format "yyyy-MM-dd"

$sb = New-Object System.Text.StringBuilder
$nl = [Environment]::NewLine
$null = $sb.Append("# Source Register$nl$nl")
$null = $sb.Append("Generated by ``scripts/build-source-register.ps1`` on $today.$nl$nl")
$null = $sb.Append("This file answers provenance questions: latest source, source platform, raw file, draft file, date range, and project history.$nl$nl")
$null = $sb.Append("Important: this register only includes material already imported into this repository.$nl$nl")
$null = $sb.Append("| Source date | Provider | Surface | Project | Title | Raw | Draft |$nl")
$null = $sb.Append("|---|---|---|---|---|---|---|$nl")

foreach ($r in $sorted) {
    $draftCell = if ([string]::IsNullOrWhiteSpace($r.DraftPath)) { "" } else { "``$($r.DraftPath)``" }
    $null = $sb.Append("| $(Escape-Cell $r.SourceDate) | $(Escape-Cell $r.Provider) | $(Escape-Cell $r.Surface) | $(Escape-Cell $r.Project) | $(Escape-Cell $r.Title) | ``$($r.RawPath)`` | $draftCell |$nl")
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)

Write-Output "Source register: $outPath"
Write-Output "Sources indexed: $($records.Count)"
